app = "escrowd"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"

[env]
  STELLAR_NETWORK = "testnet"

[processes]
  app = "./escrowd both"

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
