app = "escrowd"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"

[env]
  STELLAR_NETWORK = "testnet"

[processes]
  app = "./escrowd both"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
